#!/usr/bin/env bash
# MAC6100 — Ubuntu 24.04 build-host setup (VM on Mac, or any Linux).
# Prepares apt deps, repo checkouts, local GUI SITE, and build-local.sh.
set -euo pipefail

cd "$(dirname "$0")"
HUB_DIR="$(pwd)"

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "error: run inside Ubuntu/Linux (e.g. UTM VM), not on macOS Darwin" >&2
  echo "On the Mac host use: ./setup-macos.sh" >&2
  exit 1
fi

if ! command -v apt-get >/dev/null; then
  echo "error: expected Debian/Ubuntu with apt-get" >&2
  exit 1
fi

PROJECTS="${MAC6100_PROJECTS:-$HOME/Projects}"
IMAGES="${MAC6100_IMAGES:-$PROJECTS/images}"
BR_DIR="$PROJECTS/AetherX6100Buildroot"
GUI_DIR="$PROJECTS/x6100_test"
BR_BRANCH="${MAC6100_BR_BRANCH:-bootlogo}"
BR_TAG="${MAC6100_BR_TAG:-mac6100-baseline-1}"
GUI_BRANCH="${MAC6100_GUI_BRANCH:-main}"

BR_REPO="${MAC6100_BR_REPO:-https://github.com/HE3r0/AetherX6100Buildroot.git}"
GUI_REPO="${MAC6100_GUI_REPO:-https://github.com/HE3r0/x6100_test.git}"
HUB_REPO="${MAC6100_HUB_REPO:-https://github.com/HE3r0/MAC6100.git}"

log() { printf '==> %s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }

log "Install Buildroot / MAC6100 host packages"
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
  build-essential cmake git rsync unzip bc cpio wget curl \
  python3 flex bison g++ file patch gettext ccache \
  libncurses-dev libssl-dev device-tree-compiler u-boot-tools \
  qemu-utils squashfs-tools imagemagick

mkdir -p "$PROJECTS" "$IMAGES"

clone_or_update() {
  local url="$1" dir="$2" branch="${3:-}"
  if [[ -d "$dir/.git" ]]; then
    log "Fetch $dir"
    git -C "$dir" fetch --all --tags || warn "fetch failed: $dir"
  else
    log "Clone $url -> $dir"
    git clone "$url" "$dir"
  fi
  if [[ -n "$branch" ]]; then
    git -C "$dir" checkout "$branch" || warn "checkout $branch failed in $dir"
  fi
}

# Hub may already be this directory
if [[ ! -d "$HUB_DIR/.git" ]]; then
  clone_or_update "$HUB_REPO" "$PROJECTS/MAC6100" "main"
  HUB_DIR="$PROJECTS/MAC6100"
fi

clone_or_update "$GUI_REPO" "$GUI_DIR" "$GUI_BRANCH"
clone_or_update "$BR_REPO" "$BR_DIR" "$BR_BRANCH"

if git -C "$BR_DIR" rev-parse "$BR_TAG" >/dev/null 2>&1; then
  if [[ "${MAC6100_RESET_TO_BASELINE:-0}" == "1" ]]; then
    log "Reset Buildroot hard to $BR_TAG"
    git -C "$BR_DIR" reset --hard "$BR_TAG"
  else
    log "Tag $BR_TAG present (set MAC6100_RESET_TO_BASELINE=1 to hard-reset)"
  fi
else
  warn "Tag $BR_TAG not found — staying on $BR_BRANCH tip"
fi

MK="$BR_DIR/br2_external/package/x6100-gui/x6100_gui.mk"
if [[ -f "$MK" ]]; then
  log "Wire X6100_GUI_SITE=$GUI_DIR (local)"
  python3 - "$MK" "$GUI_DIR" <<'PY'
import pathlib, re, sys
path = pathlib.Path(sys.argv[1])
site = sys.argv[2]
text = path.read_text(encoding="utf-8", errors="replace")
path.with_suffix(path.suffix + ".bak").write_text(text, encoding="utf-8")
if re.search(r"^X6100_GUI_SITE\s*=", text, re.M):
    text = re.sub(r"^X6100_GUI_SITE\s*=\s*.*$", f"X6100_GUI_SITE = {site}", text, count=1, flags=re.M)
else:
    text += f"\nX6100_GUI_SITE = {site}\n"
if re.search(r"^X6100_GUI_SITE_METHOD\s*=", text, re.M):
    text = re.sub(r"^X6100_GUI_SITE_METHOD\s*=\s*.*$", "X6100_GUI_SITE_METHOD = local", text, count=1, flags=re.M)
else:
    text = re.sub(r"^(X6100_GUI_SITE\s*=\s*.*)$", r"\1\nX6100_GUI_SITE_METHOD = local", text, count=1, flags=re.M)
text = re.sub(r"^X6100_GUI_GIT_SUBMODULES\s*=", "# X6100_GUI_GIT_SUBMODULES =", text, flags=re.M)
path.write_text(text, encoding="utf-8")
print(path)
PY
  grep -E 'X6100_GUI_(SITE|SITE_METHOD|VERSION)' "$MK" || true
else
  warn "Missing $MK"
fi

ENV_FILE="$HUB_DIR/mac6100.local.env"
cat >"$ENV_FILE" <<EOF
# Generated by setup-buildhost.sh
export MAC6100_BUILDROOT="$BR_DIR"
export MAC6100_HUB="$HUB_DIR"
export MAC6100_WIN_PROJECTS="$IMAGES"
EOF

WRAPPER="$HUB_DIR/build-local.sh"
cat >"$WRAPPER" <<EOF
#!/usr/bin/env bash
set -euo pipefail
# shellcheck disable=SC1091
source "$ENV_FILE"
exec "$HUB_DIR/build.sh" "\$@"
EOF
chmod +x "$WRAPPER" "$HUB_DIR/build.sh" "$HUB_DIR/setup-macos.sh" 2>/dev/null || true
chmod +x "$WRAPPER"

if [[ ! -d "$BR_DIR/build" ]]; then
  warn "No build/ tree yet — first-time Buildroot config required:"
  warn "  cd $BR_DIR"
  warn "  git submodule update --init --recursive"
  warn "  ./br_config.sh"
  warn "  cd build && make"
  warn "Then: $WRAPPER"
else
  log "Existing build/ found — incremental rebuild:"
  log "  $WRAPPER"
fi

cat <<EOF

Done.

Layout:
  GUI:       $GUI_DIR  ($GUI_BRANCH)
  Buildroot: $BR_DIR  ($BR_BRANCH)
  Hub:       $HUB_DIR
  Images:    $IMAGES/sdcardN.img

Edit GUI on Mac or in the VM; always build inside this Linux host.
EOF
